# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import env_pb2 as env__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in env_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnvironmentServiceStub:
    """TODO(jbd): Migrate data plane (shell/fs) to guest.proto (ProcessService/FileSystemService).
    TODO(jbd): Remove env legacy HTTP REST endpoints for environment lifecycle.
    TODO(jbd): Update remaining examples and documentation.
    TODO(jbd): Add ListEnvironments to EnvironmentService.

    ============================================================================
    --- SERVICES ---
    ============================================================================

    EnvironmentService manages the lifecycle of isolated execution environments.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEnvironment = channel.unary_unary(
                '/ateenv.v1.EnvironmentService/CreateEnvironment',
                request_serializer=env__pb2.CreateEnvironmentRequest.SerializeToString,
                response_deserializer=env__pb2.CreateEnvironmentResponse.FromString,
                _registered_method=True)
        self.GetEnvironment = channel.unary_unary(
                '/ateenv.v1.EnvironmentService/GetEnvironment',
                request_serializer=env__pb2.GetEnvironmentRequest.SerializeToString,
                response_deserializer=env__pb2.GetEnvironmentResponse.FromString,
                _registered_method=True)
        self.SuspendEnvironment = channel.unary_unary(
                '/ateenv.v1.EnvironmentService/SuspendEnvironment',
                request_serializer=env__pb2.SuspendEnvironmentRequest.SerializeToString,
                response_deserializer=env__pb2.SuspendEnvironmentResponse.FromString,
                _registered_method=True)
        self.DeleteEnvironment = channel.unary_unary(
                '/ateenv.v1.EnvironmentService/DeleteEnvironment',
                request_serializer=env__pb2.DeleteEnvironmentRequest.SerializeToString,
                response_deserializer=env__pb2.DeleteEnvironmentResponse.FromString,
                _registered_method=True)


class EnvironmentServiceServicer:
    """TODO(jbd): Migrate data plane (shell/fs) to guest.proto (ProcessService/FileSystemService).
    TODO(jbd): Remove env legacy HTTP REST endpoints for environment lifecycle.
    TODO(jbd): Update remaining examples and documentation.
    TODO(jbd): Add ListEnvironments to EnvironmentService.

    ============================================================================
    --- SERVICES ---
    ============================================================================

    EnvironmentService manages the lifecycle of isolated execution environments.
    """

    def CreateEnvironment(self, request, context):
        """CreateEnvironment registers and starts a new environment from an actor template.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnvironment(self, request, context):
        """GetEnvironment retrieves the status and configuration of an existing environment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuspendEnvironment(self, request, context):
        """SuspendEnvironment checkpoints and stops an active environment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEnvironment(self, request, context):
        """DeleteEnvironment permanently removes an environment and its associated resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvironmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnvironment,
                    request_deserializer=env__pb2.CreateEnvironmentRequest.FromString,
                    response_serializer=env__pb2.CreateEnvironmentResponse.SerializeToString,
            ),
            'GetEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvironment,
                    request_deserializer=env__pb2.GetEnvironmentRequest.FromString,
                    response_serializer=env__pb2.GetEnvironmentResponse.SerializeToString,
            ),
            'SuspendEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.SuspendEnvironment,
                    request_deserializer=env__pb2.SuspendEnvironmentRequest.FromString,
                    response_serializer=env__pb2.SuspendEnvironmentResponse.SerializeToString,
            ),
            'DeleteEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEnvironment,
                    request_deserializer=env__pb2.DeleteEnvironmentRequest.FromString,
                    response_serializer=env__pb2.DeleteEnvironmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ateenv.v1.EnvironmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ateenv.v1.EnvironmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvironmentService:
    """TODO(jbd): Migrate data plane (shell/fs) to guest.proto (ProcessService/FileSystemService).
    TODO(jbd): Remove env legacy HTTP REST endpoints for environment lifecycle.
    TODO(jbd): Update remaining examples and documentation.
    TODO(jbd): Add ListEnvironments to EnvironmentService.

    ============================================================================
    --- SERVICES ---
    ============================================================================

    EnvironmentService manages the lifecycle of isolated execution environments.
    """

    @staticmethod
    def CreateEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ateenv.v1.EnvironmentService/CreateEnvironment',
            env__pb2.CreateEnvironmentRequest.SerializeToString,
            env__pb2.CreateEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ateenv.v1.EnvironmentService/GetEnvironment',
            env__pb2.GetEnvironmentRequest.SerializeToString,
            env__pb2.GetEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuspendEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ateenv.v1.EnvironmentService/SuspendEnvironment',
            env__pb2.SuspendEnvironmentRequest.SerializeToString,
            env__pb2.SuspendEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ateenv.v1.EnvironmentService/DeleteEnvironment',
            env__pb2.DeleteEnvironmentRequest.SerializeToString,
            env__pb2.DeleteEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
